In [1]:
import numpy as np

In [12]:
def sigmoid (x: np.array):
    return np.round(1 / (1 + np.exp(-x)), 3)

In [13]:
sigmoid(0.14), sigmoid(0.22), sigmoid(0.18-0.04+0.5)

(0.535, 0.555, 0.655)

In [14]:
sigmoid(0.1345), sigmoid(0.5205)

(0.534, 0.627)

In [24]:
0.535 * (1-0.535) * (0.116 * (-0.4) + (-0.147) * 0.2)

-0.018857145000000002

In [25]:
0.555 * (1 - 0.555) * (0.116 * 0.1 + (-0.147) * (-0.1))

0.0064954425

In [26]:
0.655 * (1- 0.655) * (0.116 * 0.6 + 0.147 * 0.2)

0.022371524999999996

In [33]:
def weight_update (w_init, x_arr, delta):
    return np.round(w_init + 0.1 * delta * x_arr, 3)

In [37]:
a = np.array([-0.1, -0.4, 0.1, 0.6]).reshape(-1, 1)
b = np.array([1, 0.535, 0.555, 0.655]).reshape(-1, 1)

edge_2_1 = weight_update(a, b, 0.116)
edge_2_1

array([[-0.088],
       [-0.394],
       [ 0.106],
       [ 0.608]])

In [38]:
a = np.array([0.6, 0.2, -0.1, -0.2]).reshape(-1, 1)
b = np.array([1, 0.535, 0.555, 0.655]).reshape(-1, 1)

edge_2_2 = weight_update(a, b, -0.147)
edge_2_2

array([[ 0.585],
       [ 0.192],
       [-0.108],
       [-0.21 ]])

In [44]:
a = np.array([0.1, 0.1, 0.2]).reshape(-1, 1)
b = np.array([1, 0.6, 0.1]).reshape(-1, 1)
edge_1_1 = weight_update(a, b, -0.0189)
edge_1_1

array([[0.098],
       [0.099],
       [0.2  ]])

In [45]:
a = np.array([0.2, 0, 0.2]).reshape(-1, 1)
b = np.array([1, 0.6, 0.1]).reshape(-1, 1)
edge_1_2 = weight_update(a, b, 0.0065)
edge_1_2

array([[0.201],
       [0.   ],
       [0.2  ]])

In [46]:
a = np.array([0.5, 0.3, -0.4]).reshape(-1, 1)
b = np.array([1, 0.6, 0.1]).reshape(-1, 1)
edge_1_3 = weight_update(a, b, 0.0024)
edge_1_3

array([[ 0.5],
       [ 0.3],
       [-0.4]])